name: Demo

on:
  schedule:
    - cron:  '0 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --editable .
      - name: run
        run: |
          python -m icsmerger -o demo.ics https://calendar.google.com/calendar/ical/6eg1noirmh70doip6aa3gsmnis@group.calendar.google.com/public/basic.ics http://i.cal.to/ical/34/fckoeln/bundesliga-spielplan/002db45d.07415847-cffb0f91.ics
      - name: Upload demo.ics
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./demo.ics
          asset_name: demo.ics
          tag: demo
          overwrite: true
